# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Resource.new(fortune: "You are a beautiful, smart, and loving person.", type: "insprational")
Resource.new(fortune: "You are like a feather in the hand, way better than a bird in the air.", type: "insprational")     
Resource.new(fortune: "A fresh start will put you on your way.", type: "insprational")
Resource.new(fortune: "You are a golden egg of opportunity.", type: "funny")
Resource.new(fortune: "A lifetime friend shall soon be made.", type: "insprational")
Resource.new(fortune: "A lifetime of happiness lies ahead of you.", type: "insprational")
Resource.new(fortune: "You have a light heart, it will carry you through all the hard times.", type: "insprational")
Resource.new(fortune: "A new perspective will come with the new year.", type: "insprational")  
Resource.new(fortune: "A pleasant surprise is waiting for you.", type: "insprational")
Resource.new(fortune: "You have a great smile!", type: "compliment")
Resource.new(fortune: "Look for a smile as brigt as your own, it will lead your way.", type: "insprational")
Resource.new(fortune: "You are on a long smooth journey! You should have great expectations.", type: "insprational")
Resource.new(fortune: "Your soft voice can be awfully persuasive.", type: "compliment")
Resource.new(fortune: "A truly rich life contains love and art in abundance. You have both." type: "compliment")
Resource.new(fortune: "Accept something that you cannot change, and you will feel better.", type: "insprational")
Resource.new(fortune: "Adventure can be real happiness.", type: "insprational")
Resource.new(fortune: "All the effort you are making will ultimately pay off.", type: "insprational")
Resource.new(fortune: "All the troubles you have will pass away very quickly.", type: "insprational")
Resource.new(fortune: "All will go well with your new project.", type: "insprational")
Resource.new(fortune: "All your hard work will soon pay off.", type: "insprational")
Resource.new(fortune: "Allow compassion to guide your decisions.", type: "insprational")
Resource.new(fortune: "An important person will offer you support.", type: "insprational")
Resource.new(fortune: "Any decision you have to make tomorrow is a good decision.", type: "insprational")
Resource.new(fortune: "At the touch of your love, everyone becomes a poet.", type: "insprational")
Resource.new(fortune: "You are a beauty, and appeal to others." type: "compliment")     
Resource.new(fortune: "Because you demand more from yourself, others respect you deeply.", type: "insprational")
Resource.new(fortune: "You believe in yourself and others will too.", type: "insprational")
Resource.new(fortune: "Bide your time, for success is near.", type: "insprational")
Resource.new(fortune: "Change is happening in your life, so go with the flow!", type: "insprational")
Resource.new(fortune: "Competence like yours is underrated.", type: "compliment")
Resource.new(fortune: "Congratulations! You are on your way.", type: "insprational")
Resource.new(fortune: "Courtesy is contagious, your are courteous... so you are also contagous.", type: "insprational")
Resource.new(fortune: "You will dedicate yourself with a calm mind to the task at hand.", type: "insprational")
Resource.new(fortune: "You are determined and capable.", type: "compliment")
Resource.new(fortune: "You will not be intimidated by the eloquence of others.", type: "insprational")
Resource.new(fortune: "Don’t be discouraged, because every wrong attempt discarded is another step forward.", type: "insprational")
Resource.new(fortune: "Prosperity will knock on your door soon.", type: "insprational")
Resource.new(fortune: "You have the education and the ability to meet life’s situations.", type: "insprational")
Resource.new(fortune: "Embrace love!", type: "insprational")
Resource.new(fortune: "You emulate what you admire in your parents.", type: "insprational")    
Resource.new(fortune: "You emulate what you respect in your friends.", type: "insprational")
Resource.new(fortune: "Like every flower, you bloom in your own sweet time.", type: "insprational")
Resource.new(fortune: "Everyday in your life is a special occasion.", type: "insprational")
Resource.new(fortune: "Everywhere you choose to go, friendly faces will greet you.", type: "insprational")
Resource.new(fortune: "Expect much of yourself and little of others.", type: "insprational")
Resource.new(fortune: "You have Fearless courage. That is the foundation of victory.", type: "compliment")
Resource.new(fortune: "Fortune Not Found: Abort, Retry, Ignore?", type: "funny")
Resource.new(fortune: "From now on your kindness will lead you to success.", type: "insprational")
Resource.new(fortune: "Get your mind set – confidence will lead you on.", type: "insprational")
Resource.new(fortune: "Go for the gold today! You’ll be the champion of whatever.", type: "insprational")
Resource.new(fortune: "Go take a rest; you deserve it.", type: "insprational")
Resource.new(fortune: "Good news will be brought to you by mail.", type: "insprational")
Resource.new(fortune: "Happiness begins with facing life with a smile and a wink.", type: "insprational")
Resource.new(fortune: "Happiness will bring you good luck.", type: "insprational")
Resource.new(fortune: "Happy life is just in front of you.", type: "insprational")
Resource.new(fortune: "Hard words break no bones, fine words butter no parsnips.", type: "funny")
Resource.new(fortune: "You will have a beautiful day.", type: "insprational")
Resource.new(fortune: "Help! I’m being held prisoner in a chinese bakery!", type: "funny")
Resource.new(fortune: "How many of you believe in psycho-kinesis? Raise my hand.", type: "funny")
Resource.new(fortune: "If you continually give, you will continually have.", type: "insprational")
Resource.new(fortune: "If you look in the right places, you can find some good offerings.", type: "insprational")
Resource.new(fortune: "You wish to see the best in others, so you show the best of yourself.", type: "insprational")
Resource.new(fortune: "Your desires are not extravagant, they will be granted.", type: "insprational")
Resource.new(fortune: "Try throwing yourself into your work.", type: "insprational")
Resource.new(fortune: "Your imagination rules.", type: "compliment")
Resource.new(fortune: "It is honorable to stand up for what is right, however unpopular it seems.", type: "inspirational")
Resource.new(fortune: "You are very courageous.", type: "compliment")
Resource.new(fortune: "When it’s time to get moving your spirits will lift accordingly.", type: "inspirational")
Resource.new(fortune: "Keep your face to the sunshine and you will never see shadows.", type: "inspirational")
Resource.new(fortune: "Let the world be filled with tranquility and goodwill.", type: "inspirational")
Resource.new(fortune: "Living with a commitment to excellence shall take you far.", type: "inspirational")
Resource.new(fortune: "Long life is in store for you.", type: "inspirational")
Resource.new(fortune: "Your love lights up the world.", type: "compliment")
Resource.new(fortune: "Many will travel to hear you speak.", type: "compliment")
Resource.new(fortune: "You cover miles one step at a time.", type:  "inspirational")
Resource.new(fortune: "Nature, time and patience are the three great physicians.", type: "inspirational")
Resource.new(fortune: "No one can walk backwards into the future.", type: "funny")
Resource.new(fortune: "Try something new.", type: "inspirational")
Resource.new(fortune: "One can never fill another’s shoes, rather he must outgrow the old shoes.", type: "funny")
Resource.new(fortune: "One of the first things you should look for in a problem is its positive side.", type: "inspirational")
Resource.new(fortune: "People are attracted by your delicate features.", type: "compliment")
Resource.new(fortune: "People find it difficult to resist your persuasive manner.", type: "compliment")
Resource.new(fortune: "Po Says: Pandas like eating bamboo, but I prefer mine dipped in chocolate.", type: "funny")
Resource.new(fortune: "Practice makes perfect.", type: "inspirational")
Resource.new(fortune: "Soon life will become more interesting.", type: "inspirational")
Resource.new(fortune: "You stand tall. Don’t look down upon yourself.", type: "inspirational")  
Resource.new(fortune: "Happiness is just next to you.", type: "inspirational")
Resource.new(fortune: "Success is a journey, not a destination.", type: "inspirational")
Resource.new(fortune: "Success is failure turned inside out.", type: "inspirational")
Resource.new(fortune: "Take the high road.", type: "inspirational")
Resource.new(fortune: "The greatest achievement in life is to stand up again after falling.", type: "inspirational")
Resource.new(fortune: "The harder you work, the luckier you get.", type: "inspirational")
Resource.new(fortune: "The only people who never fail are those who never try.", type: "inspirational")
Resource.new(fortune: "The secret to good friends is no secret to you.", type: "compliment")     
Resource.new(fortune: "The sure way to predict the future is to invent it.", type: "inspirational")
Resource.new(fortune: "You are truly generous and share, even with the undeserving.", type: "inspirational")
Resource.new(fortune: "You are truely kind.", type: "inspirational")   
Resource.new(fortune: "There’s no such thing as an ordinary cat.", type: "funny")
Resource.new(fortune: "Your caring is shown in your effort.", type: "compliment")
Resource.new(fortune: "Time and patience are called for, many surprises await you!.", type: "inspirational")
Resource.new(fortune: "You know yourself and it shows.", type: "compliment")
Resource.new(fortune: "To the world you may be one person, but to one person you may be the world.", type: "inspirational")
Resource.new(fortune: "Use your eloquence where it will do the most good.", type: "inspirational")
Resource.new(fortune: "You welcome change.", type: "inspirational")
Resource.new(fortune: "What’s hidden in an empty box?", type: "funny")
Resource.new(fortune: "Your heart is pure, your mind is clear.", type: "inspirational")
Resource.new(fortune: "You always bring others happiness.", type: "compliment")
Resource.new(fortune: "You are a person of another time.", type:"compliment")
Resource.new(fortune: "You are a talented storyteller.", type:"compliment")     
Resource.new(fortune: "You are admired by everyone for your talent and ability.", type:"compliment")
Resource.new(fortune: "You are almost there.", type:"inspirational")
Resource.new(fortune: "You are busy, but you are happy.", type:"inspirational")
Resource.new(fortune: "You are generous to an extreme and always think of the other fellow.", type: "compliment")
Resource.new(fortune: "You are modest and courteous.", type: "compliment")
Resource.new(fortune: "You are never selfish with your advice or your help.", type: "compliment")
Resource.new(fortune: "You are open-minded and quick to make new friends.", type: "compliment")  
Resource.new(fortune: "You are solid and dependable.", type: "compliment")
Resource.new(fortune: "You are talented in many ways.", type: "compliment")
Resource.new(fortune: "You are the master of every situation.", type: "compliment")  
Resource.new(fortune: "You are very expressive and positive in words, act and feeling.", type: "compliment")
Resource.new(fortune: "You are working hard.", type: "compliment")
Resource.new(fortune: "You can keep a secret.", type: "compliment")
Resource.new(fortune: "You can see a lot just by looking.", type: "compliment")
Resource.new(fortune: "You desire recognition and you will find it.", type: "inspirational")
Resource.new(fortune: "You have a deep appreciation of the arts and music.", type: "compliment")
Resource.new(fortune: "You have a deep interest in all that is artistic.", type: "compliment" )
Resource.new(fortune: "You have a friendly heart and are well admired.", type: "compliment")     
Resource.new(fortune: "You have a shrewd knack for spotting insincerity.", type: "compliment")
Resource.new(fortune: "You yearn for perfection, chase it!", type: "inspitation")
Resource.new(fortune: "You have an active mind and a keen imagination.", type: "compliment")
Resource.new(fortune: "You have an ambitious nature and may make a name for yourself.", type "compliment":)
Resource.new(fortune: "You have an unusual equipment for success, use it properly.", type: "compliment")
Resource.new(fortune: "You have exceeded what was expected.", type: "compliment")
Resource.new(fortune: "You have had a good start. Work harder!", type: "inspirational")
Resource.new(fortune: "You have the power to write your own fortune.", type: "inspirational")
Resource.new(fortune: "Your yearning for perfection will not fail you.", type: "inspirational")
Resource.new(fortune: "You know where you are going and how to get there.", type: "inspirational")
Resource.new(fortune: "You look pretty.", type: "compliment")
Resource.new(fortune: "You love challenge.", type: "compliment")
Resource.new(fortune: "You love chinese food.", type: "funny")
Resource.new(fortune: "You make people realize that there exist other beauties in the world.", type: "compliment")
Resource.new(fortune: "You never hesitate to tackle the most difficult problems.", type:)   
Resource.new(fortune: "You can do anything you put your mind to.", type: "inspirational")
Resource.new(fortune: "You understand how to have fun with others and to enjoy your solitude.", type: "compliment")
Resource.new(fortune: "You will always be surrounded by true friends.", type: "inspirational")
Resource.new(fortune: "You will always get what you want through your charm and personality.", type: "compliment")
Resource.new(fortune: "You will always have good luck in your personal affairs.", type: "inspirational")
Resource.new(fortune: "You will be a great success both in the business world and society.", type: "inspirational")     
Resource.new(fortune: "You will be blessed with longevity.", type: "inspirational")
Resource.new(fortune: "Your abilities are unparalleled.", type: "compliment")
Resource.new(fortune: "Your ability is appreciated.", type: "inspirational")
Resource.new(fortune: "Your ability to juggle many tasks will take you far.", type: "compliment")
Resource.new(fortune: "Your biggest virtue is your modesty.", type: "compliment")
Resource.new(fortune: "Your character can be described as natural and unrestrained.", type: "compliment")
Resource.new(fortune: "Your are young, gifted and attractive.", type: "compliment")
Resource.new(fortune: "Your goals are within your reach.", type: "inspirational")
Resource.new(fortune: "Your happiness is before you, not behind you! Cherish it.", type:"inspirational")
Resource.new(fortune: "Your hard work will payoff.", type: "inspirational")
Resource.new(fortune: "Your home is the center of great love.", type: "inspirational")
Resource.new(fortune: "Your ideals are well within your reach.", type: "inspirational")
Resource.new(fortune: "Your infinite capacity for patience will be rewarded sooner or later.", type: "inspirational")
Resource.new(fortune: "Your life will be happy and peaceful.", type: "inspirational")
Resource.new(fortune: "Your life will get more and more exciting.", type: "inspirational")
Resource.new(fortune: "Your love life will be happy and harmonious.", type: "inspirational")
Resource.new(fortune: "Your loyalty is a virtue.", type: "inspirational")
Resource.new(fortune: "You are alert, practical, and analytical.", type: "inspirational")
Resource.new(fortune: "Your mind is creative, original and alert.", type: "inspirational")
Resource.new(fortune: "Your mind is your greatest asset.", type: "compliment")
Resource.new(fortune: "Your quick wits are an asset to you.", type:" compliment")
Resource.new(fortune: "Your reputation is your wealth.", type: "compliment")
Resource.new(fortune: "Your success is astonishing .", type: "compliment")
Resource.new(fortune: "Your talents will be recognized and suitably rewarded.", type: "inspirational")
Resource.new(fortune: "The fortune you seek is in another cookie.", type: "funny")
Resource.new(fortune: "A closed mouth gathers no feet.", type: "funny")
Resource.new(fortune: "A foolish man listens to his heart. A wise man listens to cookies.", type: "funny")
Resource.new(fortune: "He who laughs at himself never runs out of things to laugh at.", type:"funny")
Resource.new(fortune: "He who throws dirt is losing ground.", type: "funny")
Resource.new(fortune: "Some men dream of fortunes, others dream of cookies.", type: "funny")
Resource.new(fortune: "We don’t know the future, but here’s a cookie.", type: "funny")
Resource.new(fortune: "You will be hungry again in one hour.", type: "funny")
Resource.new(fortune: "The road to riches is paved with homework.", type:)
Resource.new(fortune: "You can always find happiness at work on Friday.", type: "funny")
Resource.new(fortune: "Actions speak louder than fortune cookies.", type: "funny")
Resource.new(fortune: "Fortune not found? Abort, Retry, Ignore.", type: "funny")
Resource.new(fortune: "Help! I am being held prisoner in a fortune cookie factory.", type: "funny")
Resource.new(fortune: "It’s about time I got out of that cookie.", type: "funny")
Resource.new(fortune: "Never forget a friend. Especially if he owes you.", type: "funny")
Resource.new(fortune: "Never wear your best pants when you go to fight for freedom.", type: "funny")
Resource.new(fortune: "Only listen to the fortune cookie; disregard all other fortune telling units.", type: "funny")
Resource.new(fortune: "It is a good day to have a good day.", type: "inspirational")
Resource.new(fortune: "All fortunes are wrong except this one.", type: "funny")
Resource.new(fortune: "That wasn’t chicken.", type: "funny")
Resource.new(fortune: "You are worth a fortune.", type: "compliment")
Resource.new(fortune: "Some fortune cookies contain no fortune. Wait...", type: "funny")
Resource.new(fortune: "May you someday be carbon neutral.", type: "funny")
Resource.new(fortune: "Ask your mom instead of a cookie.", type: "funny")
Resource.new(fortune: "If a turtle doesn’t have a shell, is it naked or homeless?", type: "funny")
Resource.new(fortune: "Don’t eat the paper.", type: "funny")
Resource.new(fortune: "You delight the world with compassion, kindness and grace", type: "compliment")
Resource.new(fortune: "The early bird gets the worm, but the second mouse gets the cheese.", type: "funny")
Resource.new(fortune: "The fortune you seek is in another cookie.", type: "funny")
Resource.new(fortune: "Your reality check is about to bounce.", type: "funny")
Resource.new(fortune: "Tension is who you think you should be. Relaxation is who you are.", type: "inspirational")
Resource.new(fortune: "When blind leading the blind……..get out of the way.", type: "funny")
Resource.new(fortune: "Everyone seems normal until you get to know them.", type: "funny")
Resource.new(fortune: "Your road to glory will be rocky but fulfilling.", type: "inspirational")
Resource.new(fortune: "Nothing is impossible to a willing heart.", type: "inspirational")
Resource.new(fortune: "Don’t worry about money. The best things in life are free.", type: "inspirational")
Resource.new(fortune: "Don’t pursue happiness – create it.", type: "inspirational")
Resource.new(fortune: "If at first you don’t succeed, skydiving not for you.", type: "funny")
Resource.new(fortune: "Ninety-nine percent of all lawyers give the rest a bad name.", type: "funny")
Resource.new(fortune: "Easiest way to find lost object is buy replacement.", type: "funny")
Resource.new(fortune: "Smart husband buys wife fine china. Then she not trust him to wash it.", type: "funny")
Resource.new(fortune: "Inside every old person is young person wondering what the hell happened.", type: "funny")
Resource.new(fortune: "When chosen for jury duty, tell judge “fortune cookie say guilty!”", type: "funny")
Resource.new(fortune: "You are cleverly disguised as responsible adult.", type: "funny")
Resource.new(fortune: "Don’t eat the paper.", type: "funny")
Resource.new(fortune: "You will live long enough to open many fortune cookies.", type: "funny")
Resource.new(fortune: "Courage is not the absence of fear; it is the conquest of it.", type: "inspirational")
Resource.new(fortune: "The real kindness comes from within you.", type: "compliment")
Resource.new(fortune: "Person who eat fortune cookie get lousy dessert.", type: "funny")
Resource.new(fortune: "Okay to look at past and future. Just don’t stare.", type: "inspirational")
Resource.new(fortune: "Soup was secret family recipe made from toad. Hope you liked!", type: "funny")
Resource.new(fortune: "The older you get, the better you were.", type: "funny")
Resource.new(fortune: "Some men dream of fortunes, others dream of cookies.", type: "funny")
Resource.new(fortune: "If you want the rainbow, you have to tolerate the rain.", type: "inspirational")
Resource.new(fortune: "Person who rests on laurels gets thorn in backside.", type: "funny")
Resource.new(fortune: "Practice safe eating. Always use condiments.", type: "funny")
Resource.new(fortune: "Politicians are like diapers: change often, and for same reason.", type:"funny")
Resource.new(fortune: "When marriage outlawed, only outlaws have in-laws.", type: "funny")
Resource.new(fortune: "We don’t know the future, but here’s a cookie.", type: "funny")
Resource.new(fortune: "Fortune not found? Abort, Retry, Ignore.", type: "funny")
Resource.new(fortune: "Big journeys begin with a single step.", type: "inspirational")
Resource.new(fortune: "If you do the thing you fear, and the death of fear is certain.", type: "inspirational")