# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Resource.new(fortune: "You are a beautiful, smart, and loving person.", type: "insprational")
# Resource.new(fortune: "A dubious friend may be an enemy in camouflage.")
# Resource.new(fortune: "A faithful friend is a strong defense.")
Resource.new(fortune: "You are like a feather in the hand, way better than a bird in the air.", type: "insprational")     
Resource.new(fortune: "A fresh start will put you on your way.", type: "insprational")
# Resource.new(fortune: "A friend asks only for your time not your money.")
# Resource.new(fortune: "A friend is a present you give yourself.")
# Resource.new(fortune: "A gambler not only will lose what he has, but also will lose what he doesn’t have.")
Resource.new(fortune: "You are a golden egg of opportunity.", type: "funny")
# Resource.new(fortune: "A good friendship is often more important than a passionate romance.")
# Resource.new(fortune: "A good time to finish up old tasks.")     
# Resource.new(fortune: "A hunch is creativity trying to tell you something.")
Resource.new(fortune: "A lifetime friend shall soon be made.", type: "insprational")
Resource.new(fortune: "A lifetime of happiness lies ahead of you.", type: "insprational")
Resource.new(fortune: "You have a light heart, it will carry you through all the hard times.", type: "insprational")
Resource.new(fortune: "A new perspective will come with the new year.", type: "insprational")  
# Resource.new(fortune: "A person is never to (sic) old to learn.")    
# Resource.new(fortune: "A person of words and not deeds is like a garden full of weeds.")
Resource.new(fortune: "A pleasant surprise is waiting for you.", type: "insprational")
# Resource.new(fortune: "A short pencil is usually better than a long memory any day.")
# Resource.new(fortune: "A small donation is call for. It’s the right thing to do.")
Resource.new(fortune: "You have a great smile!", type: "compliment")
Resource.new(fortune: "Look for a smile as brigt as your own, it will lead your way.", type: "insprational")
Resource.new(fortune: "You are on a long smooth journey! You should have great expectations.", type: "insprational")
Resource.new(fortune: "Your soft voice can be awfully persuasive.", type: "compliment")
Resource.new(fortune: "A truly rich life contains love and art in abundance. You have both." type: "compliment")
Resource.new(fortune: "Accept something that you cannot change, and you will feel better.", type: "insprational")
Resource.new(fortune: "Adventure can be real happiness.")
# Resource.new(fortune: "Advice is like kissing. It costs nothing and is a pleasant thing to do.")     
# Resource.new(fortune: "Advice, when most needed, is least heeded.")
Resource.new(fortune: "All the effort you are making will ultimately pay off.")
Resource.new(fortune: "All the troubles you have will pass away very quickly.")
Resource.new(fortune: "All will go well with your new project.")
Resource.new(fortune: "All your hard work will soon pay off.")
Resource.new(fortune: "Allow compassion to guide your decisions.")
Resource.new(fortune: "An acquaintance of the past will affect you in the near future.")
Resource.new(fortune: "An agreeable romance might begin to take on the appearance.")
Resource.new(fortune: "An important person will offer you support.")
Resource.new(fortune: "An inch of time is an inch of gold.")
Resource.new(fortune: "Any decision you have to make tomorrow is a good decision.")
Resource.new(fortune: "At the touch of love, everyone becomes a poet.")
# Resource.new(fortune: "Be careful or you could fall for some tricks today.")
Resource.new(fortune: "You are a beauty, and appeal to others.")     
Resource.new(fortune: "Because you demand more from yourself, others respect you deeply.")
Resource.new(fortune: "Believe in yourself and others will too.")
Resource.new(fortune: "Believe it can be done.")
Resource.new(fortune: "Better ask twice than lose yourself once.")
Resource.new(fortune: "Bide your time, for success is near.")
Resource.new(fortune: "Carve your name on your heart and not on marble.")
Resource.new(fortune: "Change is happening in your life, so go with the flow!")
Resource.new(fortune: "Competence like yours is underrated.")
Resource.new(fortune: "Congratulations! You are on your way.")
# Resource.new(fortune: "Could I get some directions to your heart?")  
# Resource.new(fortune: "Courtesy begins in the home.")
Resource.new(fortune: "Courtesy is contagious, your are courteous... so you are also contagous.")
# Resource.new(fortune: "Curiosity kills boredom. Nothing can kill curiosity.")
Resource.new(fortune: "You will dedicate yourself with a calm mind to the task at hand.")
# Resource.new(fortune: "Depart not from the path which fate has you assigned.")
Resource.new(fortune: "You are determined and capable.")
# Resource.new(fortune: "Diligence and modesty can raise your social status.")
# Resource.new(fortune: "Disbelief destroys the magic.")
# Resource.new(fortune: "Distance yourself from the vain.")
Resource.new(fortune: "You will not be intimidated by the eloquence of others.")
# Resource.new(fortune: "Do not demand for someone’s soul if you already got his heart.")
# Resource.new(fortune: "Do not let ambitions overshadow small success.")
# Resource.new(fortune: "Do not make extra work for yourself.")
# Resource.new(fortune: "Do not underestimate yourself. Human beings have unlimited potentials.")
# Resource.new(fortune: "Do you know that the busiest person has the largest amount of time?")
Resource.new(fortune: "Don’t be discouraged, because every wrong attempt discarded is another step forward.")
# Resource.new(fortune: "Don’t confuse recklessness with confidence.")     
# Resource.new(fortune: "Don’t just spend time. Invest it.")
# Resource.new(fortune: "Don’t just think, act!")
# Resource.new(fortune: "Don’t let friends impose on you, work calmly and silently.")
# Resource.new(fortune: "Don’t let the past and useless detail choke your existence.")
# Resource.new(fortune: "Don’t let your limitations overshadow your talents.")
Resource.new(fortune: "Prosperity will knock on your door soon.")
Resource.new(fortune: "Each day, compel yourself to do something you would rather not do.")
Resource.new(fortune: "You have the education and the ability to meet life’s situations.")
Resource.new(fortune: "Embrace love!")
Resource.new(fortune: "You emulate what you admire in your parents.")    
Resource.new(fortune: "You emulate what you respect in your friends.")
Resource.new(fortune: "Like every flower, you bloom in your own sweet time.")
# Resource.new(fortune: "Every wise man started out by asking many questions.")
Resource.new(fortune: "Everyday in your life is a special occasion.")
Resource.new(fortune: "Everywhere you choose to go, friendly faces will greet you.")
Resource.new(fortune: "Expect much of yourself and little of others.")
# Resource.new(fortune: "Failure is the chance to do better next time.")
# Resource.new(fortune: "Failure is the path of lease persistence.")
# Resource.new(fortune: "Fear and desire – two sides of the same coin.")
Resource.new(fortune: "You have Fearless courage. That is the foundation of victory.")
# Resource.new(fortune: "Feeding a cow with roses does not get extra appreciation.")
# Resource.new(fortune: "First think of what you want to do; then do what you have to do.")
# Resource.new(fortune: "Follow the middle path. Neither extreme will make you happy.")
# Resource.new(fortune: "For hate is never conquered by hate. Hate is conquered by love.")
Resource.new(fortune: "For the things we have to learn before we can do them, we learn by doing them.")
Resource.new(fortune: "Fortune Not Found: Abort, Retry, Ignore?")
Resource.new(fortune: "From listening comes wisdom and from speaking repentance.")
Resource.new(fortune: "From now on your kindness will lead you to success.")
Resource.new(fortune: "Get your mind set – confidence will lead you on.")
Resource.new(fortune: "Get your mind set…confidence will lead you on.")
Resource.new(fortune: "Go for the gold today! You’ll be the champion of whatever.")
Resource.new(fortune: "Go take a rest; you deserve it.")
Resource.new(fortune: "Good news will be brought to you by mail.")
Resource.new(fortune: "Good news will come to you by mail.")
Resource.new(fortune: "Good to begin well, better to end well.")
Resource.new(fortune: "Happiness begins with facing life with a smile and a wink.")
Resource.new(fortune: "Happiness will bring you good luck.")
Resource.new(fortune: "Happy life is just in front of you.")
Resource.new(fortune: "Hard words break no bones, fine words butter no parsnips.")
Resource.new(fortune: "Have a beautiful day.")
Resource.new(fortune: "He who expects no gratitude shall never be disappointed.")    
Resource.new(fortune: "He who knows he has enough is rich.")
Resource.new(fortune: "He who knows others is wise. He who knows himself is enlightened.")
Resource.new(fortune: "Help! I’m being held prisoner in a chinese bakery!")
Resource.new(fortune: "How many of you believe in psycho-kinesis? Raise my hand.")
Resource.new(fortune: "How you look depends on where you go.")
Resource.new(fortune: "I learn by going where I have to go.")
Resource.new(fortune: "If a true sense of value is to be yours it must come through service.")
Resource.new(fortune: "If certainty were truth, we would never be wrong.")
Resource.new(fortune: "If you continually give, you will continually have.")
Resource.new(fortune: "If you look in the right places, you can find some good offerings.")
Resource.new(fortune: "If you think you can do a thing or think you can’t do a thing, you’re right.")
Resource.new(fortune: "If you wish to see the best in others, show the best of yourself.")
Resource.new(fortune: "If your desires are not extravagant, they will be granted.")
Resource.new(fortune: "If your desires are not to extravagant they will be granted.")    
Resource.new(fortune: "If you’re feeling down, try throwing yourself into your work.")
Resource.new(fortune: "Imagination rules the world.")
Resource.new(fortune: "In order to take, one must first give.")
Resource.new(fortune: "In the end all things will be known.")
Resource.new(fortune: "In this world of contradiction, It’s better to be merry than wise.")
Resource.new(fortune: "It could be better, but its [sic] good enough.")
Resource.new(fortune: "It is better to be an optimist and proven a fool than to be a pessimist and be proven right.")
Resource.new(fortune: "It is better to deal with problems before they arise.")
Resource.new(fortune: "It is honorable to stand up for what is right, however unpopular it seems.")
Resource.new(fortune: "It is worth reviewing some old lessons.")
Resource.new(fortune: "It takes courage to admit fault.")
Resource.new(fortune: "It’s not the amount of time you devote, but what you devote to the time that counts.")
Resource.new(fortune: "It’s time to get moving. Your spirits will lift accordingly.")
Resource.new(fortune: "Keep your face to the sunshine and you will never see shadows.")
Resource.new(fortune: "Let the world be filled with tranquility and goodwill.")
Resource.new(fortune: "Like the river flow into the sea. Something are just meant to be.")
Resource.new(fortune: "Listen not to vain words of empty tongue.")
Resource.new(fortune: "Listen to everyone. Ideas come from everywhere.")
Resource.new(fortune: "Living with a commitment to excellence shall take you far.")
Resource.new(fortune: "Long life is in store for you.")
Resource.new(fortune: "Love is a warm fire to keep the soul warm.")
Resource.new(fortune: "Love is like sweet medicine, good to the last drop.")
Resource.new(fortune: "Love lights up the world.")
Resource.new(fortune: "Love truth, but pardon error.")   
Resource.new(fortune: "Man is born to live and not prepared to live.")
Resource.new(fortune: "Man’s mind, once stretched by a new idea, never regains it’s original dimensions.")
Resource.new(fortune: "Many will travel to hear you speak.")
Resource.new(fortune: "Meditation with an old enemy is advised.")
Resource.new(fortune: "Miles are covered one step at a time.")
Resource.new(fortune: "Nature, time and patience are the three great physicians.")
Resource.new(fortune: "Never fear! The end of something marks the start of something new.")
Resource.new(fortune: "New ideas could be profitable.")
Resource.new(fortune: "New people will bring you new realizations, especially about big issues.")    
Resource.new(fortune: "No one can walk backwards into the future.")
Resource.new(fortune: "Nothing is more difficult, and therefore more precious, than to be able to decide.")
Resource.new(fortune: "Now is a good time to buy stock.")
Resource.new(fortune: "Now is the time to go ahead and pursue that love interest!")
Resource.new(fortune: "Now is the time to try something new")
Resource.new(fortune: "Now is the time to try something new.")
Resource.new(fortune: "Observe all men, but most of all yourself.")
Resource.new(fortune: "One can never fill another’s shoes, rather he must outgrow the old shoes.")
Resource.new(fortune: "One of the first things you should look for in a problem is its positive side.")
Resource.new(fortune: "Others can help you now.")
Resource.new(fortune: "Pennies from heaven find their way to your doorstep this year!")
Resource.new(fortune: "People are attracted by your Delicate [sic] features.")
Resource.new(fortune: "People find it difficult to resist your persuasive manner.")
Resource.new(fortune: "Perhaps you’ve been focusing too much on saving.")
Resource.new(fortune: "Physical activity will dramatically improve your outlook today.")
Resource.new(fortune: "Pick battles big enough to matter, small enough to win.")
Resource.new(fortune: "Place special emphasis on old friendship.")
Resource.new(fortune: "Please visit us at www.wontonfood.com")
Resource.new(fortune: "Po Says: Pandas like eating bamboo, but I prefer mine dipped in chocolate.")
Resource.new(fortune: "Practice makes perfect.")
Resource.new(fortune: "Protective measures will prevent costly disasters.")
Resource.new(fortune: "Put your mind into planning today. Look into the future.")
Resource.new(fortune: "Remember the birthday but never the age.")
Resource.new(fortune: "Remember to share good fortune as well as bad with your friends.")
Resource.new(fortune: "Rest has a peaceful effect on your physical and emotional health.")
Resource.new(fortune: "Resting well is as important as working hard.")
Resource.new(fortune: "Romance moves you in a new direction.")
Resource.new(fortune: "Savor your freedom – it is precious.")
Resource.new(fortune: "Say hello to others. You will have a happier day.")
Resource.new(fortune: "Self-knowledge is a life long process.")
Resource.new(fortune: "Share your joys and sorrows with your family.")
Resource.new(fortune: "Sift through your past to get a better idea of the present.")
Resource.new(fortune: "Sloth makes all things difficult; industry all easy.")
Resource.new(fortune: "Small confidences mark the onset of a friendship.")
Resource.new(fortune: "Society prepares the crime; the criminal commits it.")
Resource.new(fortune: "Someone you care about seeks reconciliation.")
Resource.new(fortune: "Soon life will become more interesting.")
Resource.new(fortune: "Stand tall. Don’t look down upon yourself.")  
Resource.new(fortune: "Staying close to home is going to be best for your morale today")
Resource.new(fortune: "Stop searching forever, happiness is just next to you.")
Resource.new(fortune: "Strong reasons make strong actions.")
Resource.new(fortune: "Success is a journey, not a destination.")
Resource.new(fortune: "Success is failure turned inside out.")
Resource.new(fortune: "Success is going from failure to failure without loss of enthusiasm.")
Resource.new(fortune: "Swimming is easy. Stay floating is hard.")
Resource.new(fortune: "Take care and sensitivity you show towards others will return to you.")
Resource.new(fortune: "Take the high road.")
Resource.new(fortune: "Technology is the art of arranging the world so we do not notice it.")
Resource.new(fortune: "The austerity you see around you covers the richness of life like a veil.")
Resource.new(fortune: "The best prediction of future is the past.")
Resource.new(fortune: "The change you started already have far-reaching effects. Be ready.")
Resource.new(fortune: "The change you started already have far-reaching effects. Be ready.")
Resource.new(fortune: "The first man gets the oyster, the second man gets the shell.")
Resource.new(fortune: "The greatest achievement in life is to stand up again after falling.")
Resource.new(fortune: "The harder you work, the luckier you get.")
Resource.new(fortune: "The night life is for you.")
Resource.new(fortune: "The one that recognizes the illusion does not act as if it is real.")
Resource.new(fortune: "The only people who never fail are those who never try.")
Resource.new(fortune: "The person who will not stand for something will fall for anything.")
Resource.new(fortune: "The philosophy of one century is the common sense of the next.")
Resource.new(fortune: "The saints are the sinners who keep on trying.")
Resource.new(fortune: "The secret to good friends is no secret to you.")     
Resource.new(fortune: "The small courtesies sweeten life, the greater ennoble it.")
Resource.new(fortune: "The smart thing to do is to begin trusting your intuitions.")
Resource.new(fortune: "The strong person understands how to withstand substantial loss.")
Resource.new(fortune: "The sure way to predict the future is to invent it.")
Resource.new(fortune: "The truly generous share, even with the undeserving.")
Resource.new(fortune: "The value lies not within any particular thing, but in the desire placed on that thing.")
Resource.new(fortune: "The weather is wonderful.")   
Resource.new(fortune: "There is no mistake so great as that of being always right.")
Resource.new(fortune: "There is no wisdom greater than kindness.")   
Resource.new(fortune: "There is not greater pleasure than seeing your lived (sic) ones prosper.")
Resource.new(fortune: "There’s no such thing as an ordinary cat.")
Resource.new(fortune: "Things don’t just happen; they happen just.")
Resource.new(fortune: "Those who care will make the effort.")
Resource.new(fortune: "Time and patience are called for many surprises await you!. (sic)")
Resource.new(fortune: "Time is precious, but truth is more precious than time")
Resource.new(fortune: "To know oneself, one should assert oneself.")
Resource.new(fortune: "To the world you may be one person, but to one person you may be the world.")
Resource.new(fortune: "Today is the conserve yourself, as things just won’t budge.")
Resource.new(fortune: "Today, your mouth might be moving but no one is listening.")
Resource.new(fortune: "Tonight you will be blinded by passion.")
Resource.new(fortune: "Use your eloquence where it will do the most good.")
Resource.new(fortune: "We first make our habits, and then our habits make us.")
Resource.new(fortune: "Welcome change.")
Resource.new(fortune: "“Welcome” is a powerful word.")
Resource.new(fortune: "Well done is better than well said.")
Resource.new(fortune: "What’s hidden in an empty box?")
Resource.new(fortune: "What’s yours in mine, and what’s mine is mine.")
Resource.new(fortune: "When more become too much. It’s same as being not enough.")
Resource.new(fortune: "When your heart is pure, your mind is clear.")
Resource.new(fortune: "Wish you happiness.")
Resource.new(fortune: "With age comes wisdom.")
Resource.new(fortune: "You (sic) adventure could lead to happiness.")
Resource.new(fortune: "You always bring others happiness.")
Resource.new(fortune: "You are a person of another time.")
Resource.new(fortune: "You are a talented storyteller.")     
Resource.new(fortune: "You are admired by everyone for your talent and ability.")
Resource.new(fortune: "You are almost there.")
Resource.new(fortune: "You are busy, but you are happy.")
Resource.new(fortune: "You are generous to an extreme and always think of the other fellow.")
Resource.new(fortune: "You are going to have some new clothes.")     
Resource.new(fortune: "You are in good hands this evening.")
Resource.new(fortune: "You are interested in higher education, whether material or spiritual.")
Resource.new(fortune: "You are modest and courteous.")
Resource.new(fortune: "You are never selfish with your advice or your help.")
Resource.new(fortune: "You are next in line for promotion in your firm.")
Resource.new(fortune: "You are offered the dream of a lifetime. Say yes!")
Resource.new(fortune: "You are open-minded and quick to make new friends.")  
Resource.new(fortune: "You are solid and dependable.")
Resource.new(fortune: "You are soon going to change your present line of work.")
Resource.new(fortune: "You are talented in many ways.")
Resource.new(fortune: "You are the master of every situation.")  
Resource.new(fortune: "You are very expressive and positive in words, act and feeling.")
Resource.new(fortune: "You are working hard.")
Resource.new(fortune: "You begin to appreciate how important it is to share your personal beliefs.")
Resource.new(fortune: "You can keep a secret.")
Resource.new(fortune: "You can see a lot just by looking.")
Resource.new(fortune: "You can’t steal second base and keep your foot on first.")
Resource.new(fortune: "You desire recognition and you will find it.")
Resource.new(fortune: "You have a deep appreciation of the arts and music.")
Resource.new(fortune: "You have a deep interest in all that is artistic.")
Resource.new(fortune: "You have a friendly heart and are well admired.")     
Resource.new(fortune: "You have a shrewd knack for spotting insincerity.")
Resource.new(fortune: "You have a yearning for perfection. (3)")
Resource.new(fortune: "You have an active mind and a keen imagination.")
Resource.new(fortune: "You have an ambitious nature and may make a name for yourself.")
Resource.new(fortune: "You have an unusual equipment for success, use it properly.")
Resource.new(fortune: "You have exceeded what was expected.")
Resource.new(fortune: "You have had a good start. Work harder!")
Resource.new(fortune: "You have the power to write your own fortune.")
Resource.new(fortune: "You have yearning for perfection.")
Resource.new(fortune: "You know where you are going and how to get there.")
Resource.new(fortune: "You look pretty.")
Resource.new(fortune: "You love challenge.")
Resource.new(fortune: "You love chinese food.")
Resource.new(fortune: "You make people realize that there exist other beauties in the world.")
Resource.new(fortune: "You never hesitate to tackle the most difficult problems.")   
Resource.new(fortune: "You never know who you touch.")
Resource.new(fortune: "You only treasure what you lost.")
Resource.new(fortune: "You seek to shield those you love and like the role of provider.")    
Resource.new(fortune: "You should be able to make money and hold on to it.")
Resource.new(fortune: "You should be able to undertake and complete anything.")
Resource.new(fortune: "You should pay for this check. Be generous.")
Resource.new(fortune: "You understand how to have fun with others and to enjoy your solitude.")
Resource.new(fortune: "You will always be surrounded by true friends.")
Resource.new(fortune: "You will always get what you want through your charm and personality.")
Resource.new(fortune: "You will always have good luck in your personal affairs.")
Resource.new(fortune: "You will be a great success both in the business world and society.")     
Resource.new(fortune: "You will be blessed with longevity.")
Resource.new(fortune: "You will be pleasantly surprised tonight.")
Resource.new(fortune: "You will be sharing great news with all the people you love.")
Resource.new(fortune: "You will be successful in your work.")
Resource.new(fortune: "You will be traveling and coming into a fortune.")
Resource.new(fortune: "You will be unusually successful in business.")
Resource.new(fortune: "You will become a great philanthropist in your later years.")
Resource.new(fortune: "You will become more and more wealthy.")
Resource.new(fortune: "You will enjoy good health.")
Resource.new(fortune: "You will enjoy good health; you will be surrounded by luxury.")
Resource.new(fortune: "You will find great contentment in the daily, routine activities.")
Resource.new(fortune: "You will have a fine capacity for the enjoyment of life.")
Resource.new(fortune: "You will have gold pieces by the bushel.")
Resource.new(fortune: "You will inherit a large sum of money.")
Resource.new(fortune: "You will make change for the better.")
Resource.new(fortune: "You will soon be surrounded by good friends and laughter.")
Resource.new(fortune: "You will take a chance in something in near future.")
Resource.new(fortune: "You will travel far and wide, both pleasure and business.")
Resource.new(fortune: "You will travel far and wide,both pleasure and business.")
Resource.new(fortune: "Your abilities are unparalleled.")
Resource.new(fortune: "Your ability is appreciated.")
Resource.new(fortune: "Your ability to juggle many tasks will take you far.")
Resource.new(fortune: "Your biggest virtue is your modesty.")
Resource.new(fortune: "Your character can be described as natural and unrestrained.")
Resource.new(fortune: "Your difficulties will strengthen you.")
Resource.new(fortune: "Your dreams are never silly; depend on them to guide you.")
Resource.new(fortune: "Your dreams are worth your best efforts to achieve them.")
Resource.new(fortune: "Your energy returns and you get things done.")
Resource.new(fortune: "Your family is young, gifted and attractive.")
Resource.new(fortune: "Your first love has never forgotten you.")
Resource.new(fortune: "Your goal will be reached very soon.")
Resource.new(fortune: "Your happiness is before you, not behind you! Cherish it.")
Resource.new(fortune: "Your hard work will payoff today.")
Resource.new(fortune: "Your heart will always make itself known through your words.")
Resource.new(fortune: "Your home is the center of great love.")
Resource.new(fortune: "Your ideals are well within your reach.")
Resource.new(fortune: "Your infinite capacity for patience will be rewarded sooner or later.")
Resource.new(fortune: "Your leadership qualities will be tested and proven.")
Resource.new(fortune: "Your life will be happy and peaceful.")
Resource.new(fortune: "Your life will get more and more exciting.")
Resource.new(fortune: "Your love life will be happy and harmonious.")
Resource.new(fortune: "Your love of music will be an important part of your life.")
Resource.new(fortune: "Your loyalty is a virtue, but not when it’s wedded with blind stubbornness.")
Resource.new(fortune: "Your mentality is alert, practical, and analytical.")
Resource.new(fortune: "Your mind is creative, original and alert.")
Resource.new(fortune: "Your mind is your greatest asset.")
Resource.new(fortune: "Your moods signal a period of change.")
Resource.new(fortune: "Your quick wits will get you out of a tough situation.")
Resource.new(fortune: "Your reputation is your wealth.")
Resource.new(fortune: "Your success will astonish everyone.")
Resource.new(fortune: "Your talents will be recognized and suitably rewarded.")
Resource.new(fortune: "Your work interests can capture the highest status or prestige.")
Resource.new(fortune: "The fortune you seek is in another cookie.")
Resource.new(fortune: "A closed mouth gathers no feet.")
Resource.new(fortune: "A conclusion is simply the place where you got tired of thinking.")
Resource.new(fortune: "A cynic is only a frustrated optimist.")
Resource.new(fortune: "A foolish man listens to his heart. A wise man listens to cookies.")
Resource.new(fortune: "You will die alone and poorly dressed.")
Resource.new(fortune: "A fanatic is one who can't change his mind, and won't change the subject.")
Resource.new(fortune: "If you look back, you’ll soon be going that way.")
Resource.new(fortune: "You will live long enough to open many fortune cookies.")
Resource.new(fortune: "An alien of some sort will be appearing to you shortly.")
Resource.new(fortune: "Do not mistake temptation for opportunity.")
Resource.new(fortune: "Flattery will go far tonight.")
Resource.new(fortune: "He who laughs at himself never runs out of things to laugh at.")
Resource.new(fortune: "He who laughs last is laughing at you.")
Resource.new(fortune: "He who throws dirt is losing ground.")
Resource.new(fortune: "Some men dream of fortunes, others dream of cookies.")
Resource.new(fortune: "The greatest danger could be your stupidity.")
Resource.new(fortune: "We don’t know the future, but here’s a cookie.")
Resource.new(fortune: "The world may be your oyster, but it doesn't mean you'll get its pearl.")
Resource.new(fortune: "You will be hungry again in one hour.")
Resource.new(fortune: "The road to riches is paved with homework.")
Resource.new(fortune: "You can always find happiness at work on Friday.")
Resource.new(fortune: "Actions speak louder than fortune cookies.")
Resource.new(fortune: "Because of your melodic nature, the moonlight never misses an appointment.")
Resource.new(fortune: "Don’t behave with cold manners.")
Resource.new(fortune: "Don’t forget you are always on our minds.")
Resource.new(fortune: "Fortune not found? Abort, Retry, Ignore.")
Resource.new(fortune: "Help! I am being held prisoner in a fortune cookie factory.")
Resource.new(fortune: "It’s about time I got out of that cookie.")
Resource.new(fortune: "Never forget a friend. Especially if he owes you.")
Resource.new(fortune: "Never wear your best pants when you go to fight for freedom.")
Resource.new(fortune: "Only listen to the fortune cookie; disregard all other fortune telling units.")
Resource.new(fortune: "It is a good day to have a good day.")
Resource.new(fortune: "All fortunes are wrong except this one.")
Resource.new(fortune: "Someone will invite you to a Karaoke party.")
Resource.new(fortune: "That wasn’t chicken.")
Resource.new(fortune: "There is no mistake so great as that of being always right.")
Resource.new(fortune: "You love Chinese food.")
Resource.new(fortune: "I am worth a fortune.")
Resource.new(fortune: "No snowflake feels responsible in an avalanche.")
Resource.new(fortune: "You will receive a fortune cookie.")
Resource.new(fortune: "Some fortune cookies contain no fortune.")
Resource.new(fortune: "Don’t let statistics do a number on you.")
Resource.new(fortune: "You are not illiterate.")
Resource.new(fortune: "May you someday be carbon neutral.")
Resource.new(fortune: "You have rice in your teeth.")
Resource.new(fortune: "Avoid taking unnecessary gambles. Lucky numbers: 12, 15, 23, 28, 37")
Resource.new(fortune: "Ask your mom instead of a cookie.")
Resource.new(fortune: "This cookie contains 117 calories.")
Resource.new(fortune: "Hard work pays off in the future. Laziness pays off now.")
Resource.new(fortune: "You think it’s a secret, but they know.")
Resource.new(fortune: "If a turtle doesn’t have a shell, is it naked or homeless?")
Resource.new(fortune: "Change is inevitable, except for vending machines.")
Resource.new(fortune: "Don’t eat the paper.")
Resource.new(fortune: "Delight the world with compassion, kindness and grace")
Resource.new(fortune: "The early bird gets the worm, but the second mouse gets the cheese.")
Resource.new(fortune: "Some days you are pigeon, some days you are statue. Today, bring umbrella.")
Resource.new(fortune: "The fortune you seek is in another cookie.")
Resource.new(fortune: "Be on the alert to recognize your prime at whatever time of your life it may occur.")
Resource.new(fortune: "Your reality check about to bounce.")
Resource.new(fortune: "Tension is who you think you should be. Relaxation is who you are.")
Resource.new(fortune: "When blind leading the blind……..get out of the way.")
Resource.new(fortune: "Everyone seems normal until you get to know them.")
Resource.new(fortune: "Only difference between rut and a grave is depth.")
Resource.new(fortune: "Experience is what you have left when everything else gone.")
Resource.new(fortune: "A closed mouth gathers no feet.")
Resource.new(fortune: "A conclusion is simply the place where you got tired of thinking.")
Resource.new(fortune: "A cynic is only a frustrated optimist.")
Resource.new(fortune: "A foolish man listens to his heart. A wise man listens to cookies.")
Resource.new(fortune: "Your road to glory will be rocky but fulfilling.")
Resource.new(fortune: "Courage is not simply one of the virtues, but the form of every virtue at the testing point.")
Resource.new(fortune: "Patience is your alley at the moment. Don’t worry!")
Resource.new(fortune: "Nothing is impossible to a willing heart.")
Resource.new(fortune: "Don’t worry about money. The best things in life are free.")
Resource.new(fortune: "Don’t pursue happiness – create it.")
Resource.new(fortune: "If at first you don’t succeed, skydiving not for you.")
Resource.new(fortune: "Ninety-nine percent of all lawyers give the rest a bad name.")
Resource.new(fortune: "Easiest way to find lost object is buy replacement.")
Resource.new(fortune: "Smart husband buys wife fine china. Then she not trust him to wash it.")
Resource.new(fortune: "Inside every old person is young person wondering what the hell happened.")
Resource.new(fortune: "When chosen for jury duty, tell judge “fortune cookie say guilty!”")
Resource.new(fortune: "Stop eating now. Food poisoning no fun.")
Resource.new(fortune: "You are cleverly disguised as responsible adult.")
Resource.new(fortune: "Tomorrow at breakfast, listen carefully: do what rice krispies tell you to.")
Resource.new(fortune: "Drive like hell, you will get there.")
Resource.new(fortune: "Hard work pays off in the future. Laziness pays off now.")
Resource.new(fortune: "You think it’s a secret, but they know.")
Resource.new(fortune: "If a turtle doesn’t have a shell, is it naked or homeless?")
Resource.new(fortune: "Change is inevitable, except for vending machines.")
Resource.new(fortune: "Don’t eat the paper.")
Resource.new(fortune: "You will die alone and poorly dressed.")
Resource.new(fortune: "A fanatic is one who can’t change his mind and won’t change the subject.")
Resource.new(fortune: "If you look back, you’ll soon be going that way.")
Resource.new(fortune: "You will live long enough to open many fortune cookies.")
Resource.new(fortune: "An alien of some sort will be appearing to you shortly.")
Resource.new(fortune: "Courage is not the absence of fear; it is the conquest of it.")
Resource.new(fortune: "Nothing is so much to be feared as fear.")
Resource.new(fortune: "All things are difficult before they are easy.")
Resource.new(fortune: "The real kindness comes from within you.")
Resource.new(fortune: "A ship in harbor is safe, but that’s not why ships are built.")
Resource.new(fortune: "Person who eat fortune cookie get lousy dessert.")
Resource.new(fortune: "Okay to look at past and future. Just don’t stare.")
Resource.new(fortune: "Wise person needs either good manners or fast reflexes.")
Resource.new(fortune: "Soup was secret family recipe made from toad. Hope you liked!")
Resource.new(fortune: "You will soon have an out of money experience.")
Resource.new(fortune: "One tequila, two tequila, three tequila, floor.")
Resource.new(fortune: "The older you get, the better you were.")
Resource.new(fortune: "Age is high price to pay for maturity.")
Resource.new(fortune: "Procrastination is art of keeping up with yesterday.")
Resource.new(fortune: "A fool and his money are soon partying.")
Resource.new(fortune: "Do not mistake temptation for opportunity.")
Resource.new(fortune: "Flattery will go far tonight.")
Resource.new(fortune: "He who laughs at himself never runs out of things to laugh at.")
Resource.new(fortune: "He who laughs last is laughing at you.")
Resource.new(fortune: "He who throws dirt is losing ground.")
Resource.new(fortune: "Some men dream of fortunes, others dream of cookies.")
Resource.new(fortune: "Someone will invite you to a Karaoke party.")
Resource.new(fortune: "That wasn’t chicken.")
Resource.new(fortune: "There is no mistake so great as that of being always right.")
Resource.new(fortune: "You love Chinese food.")
Resource.new(fortune: "I am worth a fortune.")
Resource.new(fortune: "You don’t need strength to let go of something. What you really need is understanding.")
Resource.new(fortune: "If you want the rainbow, you have to tolerate the rain.")
Resource.new(fortune: "Fear is interest paid on a debt you may not owe.")
Resource.new(fortune: "Hardly anyone knows how much is gained by ignoring the future.")
Resource.new(fortune: "The wise man is the one that makes you think that he is dumb.")
Resource.new(fortune: "The usefulness of a cup is in its emptiness.")
Resource.new(fortune: "He who throws mud loses ground.")
Resource.new(fortune: "Success lies in the hands of those who wants it.")
Resource.new(fortune: "To avoid criticism, do nothing, say nothing, be nothing.")
Resource.new(fortune: "One that would have the fruit must climb the tree.")
Resource.new(fortune: "Probability of being seen directly proportional to stupidity of act.")
Resource.new(fortune: "He who dies with most toys, still dies.")
Resource.new(fortune: "Person who rests on laurels gets thorn in backside.")
Resource.new(fortune: "Practice safe eating. Always use condiments.")
Resource.new(fortune: "Person who give self-haircut after rice wine will be buzzed.")
Resource.new(fortune: "Politicians are like diapers: change often, and for same reason.")
Resource.new(fortune: "Atheism no fun. No holidays.")
Resource.new(fortune: "Fat person not afraid of heights – afraid of widths.")
Resource.new(fortune: "You have kleptomania. Take something for it.")
Resource.new(fortune: "When marriage outlawed, only outlaws have in-laws.")
Resource.new(fortune: "Some men dream of fortunes, others dream of cookies.")
Resource.new(fortune: "The greatest danger could be your stupidity.")
Resource.new(fortune: "We don’t know the future, but here’s a cookie.")
Resource.new(fortune: "The world may be your oyster, but it doesn’t mean you’ll get its pearl.")
Resource.new(fortune: "You will be hungry again in one hour.")
Resource.new(fortune: "Don’t behave with cold manners.")
Resource.new(fortune: "Don’t forget you are always on our minds.")
Resource.new(fortune: "Fortune not found? Abort, Retry, Ignore.")
Resource.new(fortune: "Help! I am being held prisoner in a fortune cookie factory.")
Resource.new(fortune: "It’s about time I got out of that cookie.")
Resource.new(fortune: "It takes less time to do a thing right than it does to explain why you did it wrong.")
Resource.new(fortune: "Big journeys begin with a single step.")
Resource.new(fortune: "Of all our human resources, the most precious is the desire to improve.")
Resource.new(fortune: "Do the thing you fear, and the death of fear is certain.")
Resource.new(fortune: "")
Resource.new(fortune: "https://quotes.yourdictionary.com/articles/funny-fortune-cookie-sayings.html")
Resource.new(fortune: "The fortune you seek is in another cookie.")
Resource.new(fortune: "A closed mouth gathers no feet.")
Resource.new(fortune: "A conclusion is simply the place where you got tired of thinking.")
Resource.new(fortune: "A cynic is only a frustrated optimist.")
Resource.new(fortune: "A foolish man listens to his heart. A wise man listens to cookies.")
Resource.new(fortune: "You will die alone and poorly dressed.")
Resource.new(fortune: "A fanatic is one who can't change his mind, and won't change the subject.")
Resource.new(fortune: "If you look back, you’ll soon be going that way.")
Resource.new(fortune: "You will live long enough to open many fortune cookies.")
Resource.new(fortune: "An alien of some sort will be appearing to you shortly.")
Resource.new(fortune: "Do not mistake temptation for opportunity.")
Resource.new(fortune: "Flattery will go far tonight.")
Resource.new(fortune: "He who laughs at himself never runs out of things to laugh at.")
Resource.new(fortune: "He who laughs last is laughing at you.")
Resource.new(fortune: "He who throws dirt is losing ground.")
Resource.new(fortune: "Some men dream of fortunes, others dream of cookies.")
Resource.new(fortune: "The greatest danger could be your stupidity.")
Resource.new(fortune: "We don’t know the future, but here’s a cookie.")
Resource.new(fortune: "The world may be your oyster, but it doesn't mean you'll get its pearl.")
Resource.new(fortune: "You will be hungry again in one hour.")
Resource.new(fortune: "The road to riches is paved with homework.")
Resource.new(fortune: "You can always find happiness at work on Friday.")
Resource.new(fortune: "Actions speak louder than fortune cookies.")
Resource.new(fortune: "Because of your melodic nature, the moonlight never misses an appointment.")
Resource.new(fortune: "Don’t behave with cold manners.")
Resource.new(fortune: "Don’t forget you are always on our minds.")
Resource.new(fortune: "Fortune not found? Abort, Retry, Ignore.")
Resource.new(fortune: "Help! I am being held prisoner in a fortune cookie factory.")
Resource.new(fortune: "It’s about time I got out of that cookie.")
Resource.new(fortune: "Never forget a friend. Especially if he owes you.")
Resource.new(fortune: "Never wear your best pants when you go to fight for freedom.")
Resource.new(fortune: "Only listen to the fortune cookie; disregard all other fortune telling units.")
Resource.new(fortune: "It is a good day to have a good day.")
Resource.new(fortune: "All fortunes are wrong except this one.")
Resource.new(fortune: "Someone will invite you to a Karaoke party.")
Resource.new(fortune: "That wasn’t chicken.")
Resource.new(fortune: "There is no mistake so great as that of being always right.")
Resource.new(fortune: "You love Chinese food.")
Resource.new(fortune: "I am worth a fortune.")
Resource.new(fortune: "No snowflake feels responsible in an avalanche.")
Resource.new(fortune: "You will receive a fortune cookie.")
Resource.new(fortune: "Some fortune cookies contain no fortune.")
Resource.new(fortune: "Don’t let statistics do a number on you.")
Resource.new(fortune: "You are not illiterate.")
Resource.new(fortune: "May you someday be carbon neutral.")
Resource.new(fortune: "You have rice in your teeth.")
Resource.new(fortune: "Avoid taking unnecessary gambles. Lucky numbers: 12, 15, 23, 28, 37")
Resource.new(fortune: "Ask your mom instead of a cookie.")
Resource.new(fortune: "This cookie contains 117 calories.")
Resource.new(fortune: "Hard work pays off in the future. Laziness pays off now.")
Resource.new(fortune: "You think it’s a secret, but they know.")
Resource.new(fortune: "If a turtle doesn’t have a shell, is it naked or homeless?")
Resource.new(fortune: "Change is inevitable, except for vending machines.")
Resource.new(fortune: "Don’t eat the paper.")