# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Resource.new(fortune: "You are a beautiful, smart, and loving person.", subType: "insprational")
Resource.new(fortune: "You are like a feather in the hand, way better than a bird in the air.", subType: "insprational")     
Resource.new(fortune: "A fresh start will put you on your way.", subType: "insprational")
Resource.new(fortune: "You are a golden egg of opportunity.", subType: "funny")
Resource.new(fortune: "A lifetime friend shall soon be made.", subType: "insprational")
Resource.new(fortune: "A lifetime of happiness lies ahead of you.", subType: "insprational")
Resource.new(fortune: "You have a light heart, it will carry you through all the hard times.", subType: "insprational")
Resource.new(fortune: "A new perspective will come with the new year.", subType: "insprational")  
Resource.new(fortune: "A pleasant surprise is waiting for you.", subType: "insprational")
Resource.new(fortune: "You have a great smile!", subType: "compliment")
Resource.new(fortune: "Look for a smile as brigt as your own, it will lead your way.", subType: "insprational")
Resource.new(fortune: "You are on a long smooth journey! You should have great expectations.", subType: "insprational")
Resource.new(fortune: "Your soft voice can be awfully persuasive.", subType: "compliment")
Resource.new(fortune: "A truly rich life contains love and art in abundance. You have both.", subType: "compliment")
Resource.new(fortune: "Accept something that you cannot change, and you will feel better.", subType: "insprational")
Resource.new(fortune: "Adventure can be real happiness.", subType: "insprational")
Resource.new(fortune: "All the effort you are making will ultimately pay off.", subType: "insprational")
Resource.new(fortune: "All the troubles you have will pass away very quickly.", subType: "insprational")
Resource.new(fortune: "All will go well with your new project.", subType: "insprational")
Resource.new(fortune: "All your hard work will soon pay off.", subType: "insprational")
Resource.new(fortune: "Allow compassion to guide your decisions.", subType: "insprational")
Resource.new(fortune: "An important person will offer you support.", subType: "insprational")
Resource.new(fortune: "Any decision you have to make tomorrow is a good decision.", subType: "insprational")
Resource.new(fortune: "At the touch of your love, everyone becomes a poet.", subType: "insprational")
Resource.new(fortune: "You are a beauty, and appeal to others.", subType: "compliment")     
Resource.new(fortune: "Because you demand more from yourself, others respect you deeply.", subType: "insprational")
Resource.new(fortune: "You believe in yourself and others will too.", subType: "insprational")
Resource.new(fortune: "Bide your time, for success is near.", subType: "insprational")
Resource.new(fortune: "Change is happening in your life, so go with the flow!", subType: "insprational")
Resource.new(fortune: "Competence like yours is underrated.", subType: "compliment")
Resource.new(fortune: "Congratulations! You are on your way.", subType: "insprational")
Resource.new(fortune: "Courtesy is contagious, your are courteous... so you are also contagous.", subType: "insprational")
Resource.new(fortune: "You will dedicate yourself with a calm mind to the task at hand.", subType: "insprational")
Resource.new(fortune: "You are determined and capable.", subType: "compliment")
Resource.new(fortune: "You will not be intimidated by the eloquence of others.", subType: "insprational")
Resource.new(fortune: "Don’t be discouraged, because every wrong attempt discarded is another step forward.", subType: "insprational")
Resource.new(fortune: "Prosperity will knock on your door soon.", subType: "insprational")
Resource.new(fortune: "You have the education and the ability to meet life’s situations.", subType: "insprational")
Resource.new(fortune: "Embrace love!", subType: "insprational")
Resource.new(fortune: "You emulate what you admire in your parents.", subType: "insprational")    
Resource.new(fortune: "You emulate what you respect in your friends.", subType: "insprational")
Resource.new(fortune: "Like every flower, you bloom in your own sweet time.", subType: "insprational")
Resource.new(fortune: "Everyday in your life is a special occasion.", subType: "insprational")
Resource.new(fortune: "Everywhere you choose to go, friendly faces will greet you.", subType: "insprational")
Resource.new(fortune: "Expect much of yourself and little of others.", subType: "insprational")
Resource.new(fortune: "You have Fearless courage. That is the foundation of victory.", subType: "compliment")
Resource.new(fortune: "Fortune Not Found: Abort, Retry, Ignore?", subType: "funny")
Resource.new(fortune: "From now on your kindness will lead you to success.", subType: "insprational")
Resource.new(fortune: "Get your mind set – confidence will lead you on.", subType: "insprational")
Resource.new(fortune: "Go for the gold today! You’ll be the champion of whatever.", subType: "insprational")
Resource.new(fortune: "Go take a rest; you deserve it.", subType: "insprational")
Resource.new(fortune: "Good news will be brought to you by mail.", subType: "insprational")
Resource.new(fortune: "Happiness begins with facing life with a smile and a wink.", subType: "insprational")
Resource.new(fortune: "Happiness will bring you good luck.", subType: "insprational")
Resource.new(fortune: "Happy life is just in front of you.", subType: "insprational")
Resource.new(fortune: "Hard words break no bones, fine words butter no parsnips.", subType: "funny")
Resource.new(fortune: "You will have a beautiful day.", subType: "insprational")
Resource.new(fortune: "Help! I’m being held prisoner in a chinese bakery!", subType: "funny")
Resource.new(fortune: "How many of you believe in psycho-kinesis? Raise my hand.", subType: "funny")
Resource.new(fortune: "If you continually give, you will continually have.", subType: "insprational")
Resource.new(fortune: "If you look in the right places, you can find some good offerings.", subType: "insprational")
Resource.new(fortune: "You wish to see the best in others, so you show the best of yourself.", subType: "insprational")
Resource.new(fortune: "Your desires are not extravagant, they will be granted.", subType: "insprational")
Resource.new(fortune: "Try throwing yourself into your work.", subType: "insprational")
Resource.new(fortune: "Your imagination rules.", subType: "compliment")
Resource.new(fortune: "It is honorable to stand up for what is right, however unpopular it seems.", subType: "inspirational")
Resource.new(fortune: "You are very courageous.", subType: "compliment")
Resource.new(fortune: "When it’s time to get moving your spirits will lift accordingly.", subType: "inspirational")
Resource.new(fortune: "Keep your face to the sunshine and you will never see shadows.", subType: "inspirational")
Resource.new(fortune: "Let the world be filled with tranquility and goodwill.", subType: "inspirational")
Resource.new(fortune: "Living with a commitment to excellence shall take you far.", subType: "inspirational")
Resource.new(fortune: "Long life is in store for you.", subType: "inspirational")
Resource.new(fortune: "Your love lights up the world.", subType: "compliment")
Resource.new(fortune: "Many will travel to hear you speak.", subType: "compliment")
Resource.new(fortune: "You cover miles one step at a time.", subType:  "inspirational")
Resource.new(fortune: "Nature, time and patience are the three great physicians.", subType: "inspirational")
Resource.new(fortune: "No one can walk backwards into the future.", subType: "funny")
Resource.new(fortune: "Try something new.", subType: "inspirational")
Resource.new(fortune: "One can never fill another’s shoes, rather he must outgrow the old shoes.", subType: "funny")
Resource.new(fortune: "One of the first things you should look for in a problem is its positive side.", subType: "inspirational")
Resource.new(fortune: "People are attracted by your delicate features.", subType: "compliment")
Resource.new(fortune: "People find it difficult to resist your persuasive manner.", subType: "compliment")
Resource.new(fortune: "Po Says: Pandas like eating bamboo, but I prefer mine dipped in chocolate.", subType: "funny")
Resource.new(fortune: "Practice makes perfect.", subType: "inspirational")
Resource.new(fortune: "Soon life will become more interesting.", subType: "inspirational")
Resource.new(fortune: "You stand tall. Don’t look down upon yourself.", subType: "inspirational")  
Resource.new(fortune: "Happiness is just next to you.", subType: "inspirational")
Resource.new(fortune: "Success is a journey, not a destination.", subType: "inspirational")
Resource.new(fortune: "Success is failure turned inside out.", subType: "inspirational")
Resource.new(fortune: "Take the high road.", subType: "inspirational")
Resource.new(fortune: "The greatest achievement in life is to stand up again after falling.", subType: "inspirational")
Resource.new(fortune: "The harder you work, the luckier you get.", subType: "inspirational")
Resource.new(fortune: "The only people who never fail are those who never try.", subType: "inspirational")
Resource.new(fortune: "The secret to good friends is no secret to you.", subType: "compliment")     
Resource.new(fortune: "The sure way to predict the future is to invent it.", subType: "inspirational")
Resource.new(fortune: "You are truly generous and share, even with the undeserving.", subType: "inspirational")
Resource.new(fortune: "You are truely kind.", subType: "inspirational")   
Resource.new(fortune: "There’s no such thing as an ordinary cat.", subType: "funny")
Resource.new(fortune: "Your caring is shown in your effort.", subType: "compliment")
Resource.new(fortune: "Time and patience are called for, many surprises await you!.", subType: "inspirational")
Resource.new(fortune: "You know yourself and it shows.", subType: "compliment")
Resource.new(fortune: "To the world you may be one person, but to one person you may be the world.", subType: "inspirational")
Resource.new(fortune: "Use your eloquence where it will do the most good.", subType: "inspirational")
Resource.new(fortune: "You welcome change.", subType: "inspirational")
Resource.new(fortune: "What’s hidden in an empty box?", subType: "funny")
Resource.new(fortune: "Your heart is pure, your mind is clear.", subType: "inspirational")
Resource.new(fortune: "You always bring others happiness.", subType: "compliment")
Resource.new(fortune: "You are a person of another time.", subType:"compliment")
Resource.new(fortune: "You are a talented storyteller.", subType:"compliment")     
Resource.new(fortune: "You are admired by everyone for your talent and ability.", subType:"compliment")
Resource.new(fortune: "You are almost there.", subType:"inspirational")
Resource.new(fortune: "You are busy, but you are happy.", subType:"inspirational")
Resource.new(fortune: "You are generous to an extreme and always think of the other fellow.", subType: "compliment")
Resource.new(fortune: "You are modest and courteous.", subType: "compliment")
Resource.new(fortune: "You are never selfish with your advice or your help.", subType: "compliment")
Resource.new(fortune: "You are open-minded and quick to make new friends.", subType: "compliment")  
Resource.new(fortune: "You are solid and dependable.", subType: "compliment")
Resource.new(fortune: "You are talented in many ways.", subType: "compliment")
Resource.new(fortune: "You are the master of every situation.", subType: "compliment")  
Resource.new(fortune: "You are very expressive and positive in words, act and feeling.", subType: "compliment")
Resource.new(fortune: "You are working hard.", subType: "compliment")
Resource.new(fortune: "You can keep a secret.", subType: "compliment")
Resource.new(fortune: "You can see a lot just by looking.", subType: "compliment")
Resource.new(fortune: "You desire recognition and you will find it.", subType: "inspirational")
Resource.new(fortune: "You have a deep appreciation of the arts and music.", subType: "compliment")
Resource.new(fortune: "You have a deep interest in all that is artistic.", subType: "compliment" )
Resource.new(fortune: "You have a friendly heart and are well admired.", subType: "compliment")     
Resource.new(fortune: "You have a shrewd knack for spotting insincerity.", subType: "compliment")
Resource.new(fortune: "You yearn for perfection, chase it!", subType: "inspitation")
Resource.new(fortune: "You have an active mind and a keen imagination.", subType: "compliment")
Resource.new(fortune: "You have an ambitious nature and may make a name for yourself.", subType: "compliment")
Resource.new(fortune: "You have an unusual equipment for success, use it properly.", subType: "compliment")
Resource.new(fortune: "You have exceeded what was expected.", subType: "compliment")
Resource.new(fortune: "You have had a good start. Work harder!", subType: "inspirational")
Resource.new(fortune: "You have the power to write your own fortune.", subType: "inspirational")
Resource.new(fortune: "Your yearning for perfection will not fail you.", subType: "inspirational")
Resource.new(fortune: "You know where you are going and how to get there.", subType: "inspirational")
Resource.new(fortune: "You look pretty.", subType: "compliment")
Resource.new(fortune: "You love challenge.", subType: "compliment")
Resource.new(fortune: "You love chinese food.", subType: "funny")
Resource.new(fortune: "You make people realize that there exist other beauties in the world.", subType: "compliment")
Resource.new(fortune: "You never hesitate to tackle the most difficult problems.", subType: "compliment")   
Resource.new(fortune: "You can do anything you put your mind to.", subType: "inspirational")
Resource.new(fortune: "You understand how to have fun with others and to enjoy your solitude.", subType: "compliment")
Resource.new(fortune: "You will always be surrounded by true friends.", subType: "inspirational")
Resource.new(fortune: "You will always get what you want through your charm and personality.", subType: "compliment")
Resource.new(fortune: "You will always have good luck in your personal affairs.", subType: "inspirational")
Resource.new(fortune: "You will be a great success both in the business world and society.", subType: "inspirational")     
Resource.new(fortune: "You will be blessed with longevity.", subType: "inspirational")
Resource.new(fortune: "Your abilities are unparalleled.", subType: "compliment")
Resource.new(fortune: "Your ability is appreciated.", subType: "inspirational")
Resource.new(fortune: "Your ability to juggle many tasks will take you far.", subType: "compliment")
Resource.new(fortune: "Your biggest virtue is your modesty.", subType: "compliment")
Resource.new(fortune: "Your character can be described as natural and unrestrained.", subType: "compliment")
Resource.new(fortune: "Your are young, gifted and attractive.", subType: "compliment")
Resource.new(fortune: "Your goals are within your reach.", subType: "inspirational")
Resource.new(fortune: "Your happiness is before you, not behind you! Cherish it.", subType:"inspirational")
Resource.new(fortune: "Your hard work will payoff.", subType: "inspirational")
Resource.new(fortune: "Your home is the center of great love.", subType: "inspirational")
Resource.new(fortune: "Your ideals are well within your reach.", subType: "inspirational")
Resource.new(fortune: "Your infinite capacity for patience will be rewarded sooner or later.", subType: "inspirational")
Resource.new(fortune: "Your life will be happy and peaceful.", subType: "inspirational")
Resource.new(fortune: "Your life will get more and more exciting.", subType: "inspirational")
Resource.new(fortune: "Your love life will be happy and harmonious.", subType: "inspirational")
Resource.new(fortune: "Your loyalty is a virtue.", subType: "inspirational")
Resource.new(fortune: "You are alert, practical, and analytical.", subType: "inspirational")
Resource.new(fortune: "Your mind is creative, original and alert.", subType: "inspirational")
Resource.new(fortune: "Your mind is your greatest asset.", subType: "compliment")
Resource.new(fortune: "Your quick wits are an asset to you.", subType:" compliment")
Resource.new(fortune: "Your reputation is your wealth.", subType: "compliment")
Resource.new(fortune: "Your success is astonishing .", subType: "compliment")
Resource.new(fortune: "Your talents will be recognized and suitably rewarded.", subType: "inspirational")
Resource.new(fortune: "The fortune you seek is in another cookie.", subType: "funny")
Resource.new(fortune: "A closed mouth gathers no feet.", subType: "funny")
Resource.new(fortune: "A foolish man listens to his heart. A wise man listens to cookies.", subType: "funny")
Resource.new(fortune: "He who laughs at himself never runs out of things to laugh at.", subType:"funny")
Resource.new(fortune: "He who throws dirt is losing ground.", subType: "funny")
Resource.new(fortune: "Some men dream of fortunes, others dream of cookies.", subType: "funny")
Resource.new(fortune: "We don’t know the future, but here’s a cookie.", subType: "funny")
Resource.new(fortune: "You will be hungry again in one hour.", subType: "funny")
Resource.new(fortune: "The road to riches is paved with homework.", subType: "funny")
Resource.new(fortune: "You can always find happiness at work on Friday.", subType: "funny")
Resource.new(fortune: "Actions speak louder than fortune cookies.", subType: "funny")
Resource.new(fortune: "Fortune not found? Abort, Retry, Ignore.", subType: "funny")
Resource.new(fortune: "Help! I am being held prisoner in a fortune cookie factory.", subType: "funny")
Resource.new(fortune: "It’s about time I got out of that cookie.", subType: "funny")
Resource.new(fortune: "Never forget a friend. Especially if he owes you.", subType: "funny")
Resource.new(fortune: "Never wear your best pants when you go to fight for freedom.", subType: "funny")
Resource.new(fortune: "Only listen to the fortune cookie; disregard all other fortune telling units.", subType: "funny")
Resource.new(fortune: "It is a good day to have a good day.", subType: "inspirational")
Resource.new(fortune: "All fortunes are wrong except this one.", subType: "funny")
Resource.new(fortune: "That wasn’t chicken.", subType: "funny")
Resource.new(fortune: "You are worth a fortune.", subType: "compliment")
Resource.new(fortune: "Some fortune cookies contain no fortune. Wait...", subType: "funny")
Resource.new(fortune: "May you someday be carbon neutral.", subType: "funny")
Resource.new(fortune: "Ask your mom instead of a cookie.", subType: "funny")
Resource.new(fortune: "If a turtle doesn’t have a shell, is it naked or homeless?", subType: "funny")
Resource.new(fortune: "Don’t eat the paper.", subType: "funny")
Resource.new(fortune: "You delight the world with compassion, kindness and grace", subType: "compliment")
Resource.new(fortune: "The early bird gets the worm, but the second mouse gets the cheese.", subType: "funny")
Resource.new(fortune: "The fortune you seek is in another cookie.", subType: "funny")
Resource.new(fortune: "Your reality check is about to bounce.", subType: "funny")
Resource.new(fortune: "Tension is who you think you should be. Relaxation is who you are.", subType: "inspirational")
Resource.new(fortune: "When blind leading the blind……..get out of the way.", subType: "funny")
Resource.new(fortune: "Everyone seems normal until you get to know them.", subType: "funny")
Resource.new(fortune: "Your road to glory will be rocky but fulfilling.", subType: "inspirational")
Resource.new(fortune: "Nothing is impossible to a willing heart.", subType: "inspirational")
Resource.new(fortune: "Don’t worry about money. The best things in life are free.", subType: "inspirational")
Resource.new(fortune: "Don’t pursue happiness – create it.", subType: "inspirational")
Resource.new(fortune: "If at first you don’t succeed, skydiving not for you.", subType: "funny")
Resource.new(fortune: "Ninety-nine percent of all lawyers give the rest a bad name.", subType: "funny")
Resource.new(fortune: "Easiest way to find lost object is buy replacement.", subType: "funny")
Resource.new(fortune: "Smart husband buys wife fine china. Then she not trust him to wash it.", subType: "funny")
Resource.new(fortune: "Inside every old person is young person wondering what the hell happened.", subType: "funny")
Resource.new(fortune: "When chosen for jury duty, tell judge “fortune cookie say guilty!”", subType: "funny")
Resource.new(fortune: "You are cleverly disguised as responsible adult.", subType: "funny")
Resource.new(fortune: "Don’t eat the paper.", subType: "funny")
Resource.new(fortune: "You will live long enough to open many fortune cookies.", subType: "funny")
Resource.new(fortune: "Courage is not the absence of fear; it is the conquest of it.", subType: "inspirational")
Resource.new(fortune: "The real kindness comes from within you.", subType: "compliment")
Resource.new(fortune: "Person who eat fortune cookie get lousy dessert.", subType: "funny")
Resource.new(fortune: "Okay to look at past and future. Just don’t stare.", subType: "inspirational")
Resource.new(fortune: "Soup was secret family recipe made from toad. Hope you liked!", subType: "funny")
Resource.new(fortune: "The older you get, the better you were.", subType: "funny")
Resource.new(fortune: "Some men dream of fortunes, others dream of cookies.", subType: "funny")
Resource.new(fortune: "If you want the rainbow, you have to tolerate the rain.", subType: "inspirational")
Resource.new(fortune: "Person who rests on laurels gets thorn in backside.", subType: "funny")
Resource.new(fortune: "Practice safe eating. Always use condiments.", subType: "funny")
Resource.new(fortune: "Politicians are like diapers: change often, and for same reason.", subType:"funny")
Resource.new(fortune: "When marriage outlawed, only outlaws have in-laws.", subType: "funny")
Resource.new(fortune: "We don’t know the future, but here’s a cookie.", subType: "funny")
Resource.new(fortune: "Fortune not found? Abort, Retry, Ignore.", subType: "funny")
Resource.new(fortune: "Big journeys begin with a single step.", subType: "inspirational")
Resource.new(fortune: "If you do the thing you fear, and the death of fear is certain.", subType: "inspirational")